//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceSoft.RetailPlus.MasterFiles._ProductGroup {
    
    
    public partial class _Default {
        
        /// <summary>
        /// frmProductGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm frmProductGroup;
        
        /// <summary>
        /// ToolkitScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
        
        /// <summary>
        /// ctrlProcessing control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.@__Processing ctrlProcessing;
        
        /// <summary>
        /// PageHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.@__PageHeader PageHeader;
        
        /// <summary>
        /// HorizontalNavBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.@__HorizontalNavBar HorizontalNavBar;
        
        /// <summary>
        /// ctrlExpiry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.@__Expiry ctrlExpiry;
        
        /// <summary>
        /// SiteTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.@__SiteTitle SiteTitle;
        
        /// <summary>
        /// LargeHeading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.@__LargeHeading LargeHeading;
        
        /// <summary>
        /// RightBodySectionSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.@__RightBodySectionSearch RightBodySectionSearch;
        
        /// <summary>
        /// ctrlMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.MasterFiles.@__Menu ctrlMenu;
        
        /// <summary>
        /// PageLevelError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.@__PageLevelError PageLevelError;
        
        /// <summary>
        /// ctrlList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.MasterFiles._ProductGroup.@__List ctrlList;
        
        /// <summary>
        /// ctrlInsert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.MasterFiles._ProductGroup.@__Insert ctrlInsert;
        
        /// <summary>
        /// ctrlUpdate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.MasterFiles._ProductGroup.@__Update ctrlUpdate;
        
        /// <summary>
        /// ctrlDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AceSoft.RetailPlus.MasterFiles._ProductGroup.@__Details ctrlDetails;
    }
}
