UPDATE tblTransactionItems01 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems02 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems03 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems04 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems05 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems06 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems07 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems08 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems09 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems10 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems11 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactionItems12 SET vatableamount = amount/(1+(VAT/100));
UPDATE tblTransactions02 SET cashiername = (select name from sysaccessuserdetails where tblTransactions02.cashierid=sysaccessuserdetails.uid) where cashiername <> (select name from sysaccessuserdetails where tblTransactions02.cashierid=sysaccessuserdetails.uid);