
DROP TABLE FE_DSC;
CREATE TABLE FE_DSC(
	SVRKEY VARCHAR(300),
	DSRKEY VARCHAR(300),
	DSDESC VARCHAR(300),
	DSBDAY VARCHAR(300),
	DSADR1 VARCHAR(300),
	DSADR2 VARCHAR(300),
	DSPONE VARCHAR(300),
	LASTSS VARCHAR(300),
	DS_AMT VARCHAR(300),
	DS_PTS VARCHAR(300),
	DS_RED VARCHAR(300),
	DSWIFE VARCHAR(300),
	DSRNAM VARCHAR(300),
	DSRNUM VARCHAR(300),
	DSRKY1 VARCHAR(300),
	DSRKY2 VARCHAR(300),
	DSRKY3 VARCHAR(300),
	DSRKY4 VARCHAR(300),
	DSRKY5 VARCHAR(300),
	DSTATS VARCHAR(300),
	USERID VARCHAR(300),
	USRDAT VARCHAR(300),
	USRFUN VARCHAR(300),
	STATUS VARCHAR(300)
);
CREATE INDEX IX_FE_DSC ON FE_DSC (DSRKEY);
CREATE INDEX IX1_FE_DSC ON FE_DSC (DSDESC);


INSERT INTO tblContactGroup(ContactGroupID, ContactGroupCode, ContactGroupName, ContactGroupCategory, CreatedOn, LastModified)VALUES(6, 'ADV Member', 'ADV Member', 1, NOW(), NOW());

