/*****************************
**	tblgla_order_tender
*****************************/
DROP TABLE IF EXISTS tblgla_order_tender;
CREATE TABLE tblgla_order_tender (
	`identifier` VARCHAR(50) NULL,
	`order_hdr_id` BIGINT NOT NULL DEFAULT 0 COMMENT 'Reference: tblgla_f_dtl_chk_headers.chk_headers_seq_number',
	`tender_seq` BIGINT NOT NULL DEFAULT 0,
	`tender_id` BIGINT NOT NULL DEFAULT 0,
	`tender_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`prorata_sales_amt_gross` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`prorata_discount_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`prorata_tax_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`prorata_grat_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`prorata_svc_chg_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`tip_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`breakage_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`received_curr_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`curr_decimal_places` INT NOT NULL DEFAULT 0 COMMENT 'Number of decimal places required to print on report for this foregin currency',
	`exchange_rate` INT NOT NULL DEFAULT 0,
	`change_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`change_tender_id` INT NOT NULL DEFAULT 0,
	`tax_removed_code` INT NOT NULL DEFAULT 0,
	`tender_type_id` INT NOT NULL DEFAULT 0,
	`subtender_id` INT NOT NULL DEFAULT 0,
	`auth_acct_no` VARCHAR(250) NULL,
	`post_acct_no` VARCHAR(250) NULL,
	`customer_name` VARCHAR(250) NULL COMMENT 'Customer name for Credit Card, room, PMSI, GA, Comp, Coupon=null',
	`adtnl_info` VARCHAR(400) NULL COMMENT 'Additional input from the terminal',
	`subtender_qty` INT NOT NULL DEFAULT 0,
	`charges_to_date_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`remaining_balance_amt` DECIMAL(18,3) NOT NULL DEFAULT 0,
	`PMS_post_flag` TINYINT(1) NOT NULL DEFAULT 0,
	`sales_tippable_flag` TINYINT(1) NOT NULL DEFAULT 0,
	`post_system1_flag` TINYINT(1) NOT NULL DEFAULT 0,
	`post_system2_flag` TINYINT(1) NOT NULL DEFAULT 0,
	`post_system3_flag` TINYINT(1) NOT NULL DEFAULT 0,
	`post_system4_flag` TINYINT(1) NOT NULL DEFAULT 0,
	`post_system5_flag` TINYINT(1) NOT NULL DEFAULT 0,
	`post_system6_flag` TINYINT(1) NOT NULL DEFAULT 0,
	`post_system7_flag` TINYINT(1) NOT NULL DEFAULT 0,
	`DateCreated` DATETIME NOT NULL DEFAULT NOW(),
	`CreatedBy` VARCHAR(120) NULL,
	`Filename` VARCHAR(120) NULL,
	`BatchID` VARCHAR(30) NULL,
INDEX `IX_tblgla_order_tender`(`order_hdr_id`),
INDEX `IX1_tblgla_order_tender`(`customer_name`)
);
